org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod
mod_version=1.20.1-2.1.6.3

# Minecraft
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

# Loader
forge_version=47.4.22
forge_version_range=[47,)
loader_version_range=[47,)

# Mappings
mapping_channel=official
mapping_version=1.20.1

# Mod metadata
mod_id=champions
mod_name=Champions
mod_group_id=top.theillusivec4.champions
mod_authors=C4
mod_description=Creates elite mobs of different rarities, with enhanced stats and extra abilities.
